export interface ITooltipData {
    axisDim: string,
    axisId: string,
    axisIndex: number,
    axisType: string,
    axisValue: string,
    axisValueLabel: string,
    borderColor: string,
    color: string,
    componentIndex: number,
    componentSubType: string,
    componentType: 'series',
    data: Array<any>,
    dataIndex: number,
    dataType: any,
    dimensionNames: Array<string>,
    encode: Object,
    marker: string,
    name: string,
    seriesId: string,
    seriesIndex: number,
    seriesName: string,
    seriesType: string,
    value: Array<any>,
    percent: number,
}